const SMS_ACTIVATE_COUNTRY_ISO: Record<string, string> = {
  '0': 'RU',
  '1': 'UA',
  '2': 'KZ',
  '3': 'CN',
  '4': 'PH',
  '5': 'MM',
  '6': 'ID',
  '7': 'MY',
  '8': 'KE',
  '9': 'TZ',
  '10': 'VN',
  '11': 'KG',
  '12': 'US',
  '13': 'IL',
  '14': 'HK',
  '15': 'PL',
  '16': 'GB',
  '17': 'MG',
  '18': 'CD',
  '19': 'NG',
  '20': 'MO',
  '21': 'EG',
  '22': 'IN',
  '23': 'IE',
  '24': 'KH',
  '25': 'LA',
  '26': 'HT',
  '27': 'CI',
  '28': 'GM',
  '29': 'RS',
  '30': 'YE',
  '31': 'ZA',
  '32': 'RO',
  '33': 'CO',
  '34': 'EE',
  '35': 'AZ',
  '36': 'CA',
  '37': 'MA',
  '38': 'GH',
  '39': 'AR',
  '40': 'UZ',
  '41': 'CM',
  '42': 'TD',
  '43': 'DE',
  '44': 'LT',
  '45': 'HR',
  '46': 'SE',
  '47': 'IQ',
  '48': 'NL',
  '49': 'LV',
  '50': 'AT',
  '51': 'BY',
  '52': 'TH',
  '53': 'SA',
  '54': 'MX',
  '55': 'TW',
  '56': 'ES',
  '57': 'IR',
  '58': 'DZ',
  '59': 'SI',
  '60': 'BD',
  '61': 'SN',
  '62': 'TR',
  '63': 'CZ',
  '64': 'LK',
  '65': 'PE',
  '66': 'PK',
  '67': 'NZ',
  '68': 'GN',
  '69': 'ML',
  '70': 'VE',
  '71': 'ET',
  '72': 'MN',
  '73': 'BR',
  '74': 'AF',
  '75': 'UG',
  '76': 'AO',
  '77': 'CY',
  '78': 'FR',
  '79': 'PG',
  '80': 'MZ',
  '81': 'NP',
  '82': 'BE',
  '83': 'BG',
  '84': 'HU',
  '85': 'MD',
  '86': 'IT',
  '87': 'PY',
  '88': 'HN',
  '89': 'TN',
  '90': 'NI',
  '91': 'TL',
  '92': 'BO',
  '93': 'CR',
  '94': 'GT',
  '95': 'AE',
  '96': 'ZW',
  '97': 'PR',
  '98': 'SD',
  '99': 'TG',
  '100': 'KW',
  '101': 'SV',
  '102': 'LY',
  '103': 'JM',
  '104': 'TT',
  '105': 'EC',
  '106': 'SZ',
  '107': 'OM',
  '108': 'BA',
  '109': 'DO',
  '110': 'SY',
  '111': 'QA',
  '112': 'PA',
  '113': 'CU',
  '114': 'MR',
  '115': 'SL',
  '116': 'JO',
  '117': 'PT',
  '118': 'BB',
  '119': 'BI',
  '120': 'BJ',
  '121': 'BN',
  '122': 'BS',
  '123': 'BW',
  '124': 'BZ',
  '125': 'CF',
  '126': 'DM',
  '127': 'GD',
  '128': 'GE',
  '129': 'GR',
  '130': 'GW',
  '131': 'GY',
  '132': 'IS',
  '133': 'KM',
  '134': 'KN',
  '135': 'LR',
  '136': 'LS',
  '137': 'MW',
  '138': 'NA',
  '139': 'NE',
  '140': 'RW',
  '141': 'SK',
  '142': 'SR',
  '143': 'TJ',
  '144': 'MC',
  '145': 'BH',
  '146': 'RE',
  '147': 'ZM',
  '148': 'AM',
  '149': 'SO',
  '150': 'CG',
  '151': 'CL',
  '152': 'BF',
  '153': 'LB',
  '154': 'GA',
  '155': 'AL',
  '156': 'UY',
  '157': 'MU',
  '158': 'BT',
  '159': 'MV',
  '160': 'GP',
  '161': 'TM',
  '162': 'GF',
  '163': 'FI',
  '164': 'LC',
  '165': 'LU',
  '166': 'VC',
  '167': 'GQ',
  '168': 'DJ',
  '169': 'AG',
  '170': 'KY',
  '171': 'ME',
  '172': 'DK',
  '173': 'CH',
  '174': 'NO',
  '175': 'AU',
  '176': 'ER',
  '177': 'SS',
  '178': 'ST',
  '179': 'AW',
  '180': 'MS',
  '181': 'AI',
  '182': 'JP',
  '183': 'MK',
  '184': 'SC',
  '185': 'NC',
  '186': 'CV',
  '187': 'US',
  '189': 'FJ',
  '196': 'SG',
  '1001': 'JP',
};

const COUNTRY_NAME_ISO: Record<string, string> = {
  japan: 'JP',
  '日本': 'JP',
  us: 'US',
  usa: 'US',
  unitedstates: 'US',
  'united states': 'US',
  '美国': 'US',
  singapore: 'SG',
  '新加坡': 'SG',
  canada: 'CA',
  '加拿大': 'CA',
  australia: 'AU',
  '澳大利亚': 'AU',
  '英国': 'GB',
  uk: 'GB',
  'united kingdom': 'GB',
  germany: 'DE',
  '德国': 'DE',
  falklandislands: 'FK',
  'falkland islands': 'FK',
  falklandislandsmalvinas: 'FK',
  niue: 'NU',
  timorleste: 'TL',
  'timor-leste': 'TL',
  easttimor: 'TL',
  'east timor': 'TL',
  vanuatu: 'VU',
  sanmarino: 'SM',
  'san marino': 'SM',
};

const COUNTRY_CALLING_CODES: Record<string, string> = {
  US: '1',
  CA: '1',
  JP: '81',
  SG: '65',
  GB: '44',
  AU: '61',
  DE: '49',
  FR: '33',
  IT: '39',
  ES: '34',
  NL: '31',
  BR: '55',
  MX: '52',
  IN: '91',
  ID: '62',
  PH: '63',
  MY: '60',
  TH: '66',
  TL: '670',
  VN: '84',
  VU: '678',
  TR: '90',
  AE: '971',
  SA: '966',
  KR: '82',
  HK: '852',
  TW: '886',
  CN: '86',
  RU: '7',
  KZ: '7',
  FK: '500',
  NU: '683',
  SM: '378',
};

const COUNTRY_CHINESE_NAMES: Record<string, string> = {
  AD: '安道尔',
  AE: '阿拉伯联合酋长国',
  AF: '阿富汗',
  AG: '安提瓜和巴布达',
  AI: '安圭拉',
  AL: '阿尔巴尼亚',
  AM: '亚美尼亚',
  AO: '安哥拉',
  AR: '阿根廷',
  AS: '美属萨摩亚',
  AT: '奥地利',
  AU: '澳大利亚',
  AW: '阿鲁巴',
  AZ: '阿塞拜疆',
  BA: '波斯尼亚和黑塞哥维那',
  BB: '巴巴多斯',
  BD: '孟加拉国',
  BE: '比利时',
  BF: '布基纳法索',
  BG: '保加利亚',
  BH: '巴林',
  BI: '布隆迪',
  BJ: '贝宁',
  BM: '百慕大',
  BN: '文莱',
  BO: '玻利维亚',
  BR: '巴西',
  BS: '巴哈马',
  BT: '不丹',
  BW: '博茨瓦纳',
  BY: '白俄罗斯',
  BZ: '伯利兹',
  CA: '加拿大',
  CD: '刚果（金）',
  CF: '中非共和国',
  CG: '刚果（布）',
  CH: '瑞士',
  CI: '科特迪瓦',
  CL: '智利',
  CM: '喀麦隆',
  CN: '中国',
  CO: '哥伦比亚',
  CR: '哥斯达黎加',
  CU: '古巴',
  CV: '佛得角',
  CY: '塞浦路斯',
  CZ: '捷克',
  DE: '德国',
  DJ: '吉布提',
  DK: '丹麦',
  DM: '多米尼克',
  DO: '多米尼加共和国',
  DZ: '阿尔及利亚',
  EC: '厄瓜多尔',
  EE: '爱沙尼亚',
  EG: '埃及',
  ER: '厄立特里亚',
  ES: '西班牙',
  ET: '埃塞俄比亚',
  FI: '芬兰',
  FK: '福克兰群岛',
  FJ: '斐济',
  FR: '法国',
  GA: '加蓬',
  GB: '英国',
  GD: '格林纳达',
  GE: '格鲁吉亚',
  GF: '法属圭亚那',
  GH: '加纳',
  GM: '冈比亚',
  GN: '几内亚',
  GP: '瓜德罗普',
  GQ: '赤道几内亚',
  GR: '希腊',
  GT: '危地马拉',
  GW: '几内亚比绍',
  GY: '圭亚那',
  HK: '香港',
  HN: '洪都拉斯',
  HR: '克罗地亚',
  HT: '海地',
  HU: '匈牙利',
  ID: '印度尼西亚',
  IE: '爱尔兰',
  IL: '以色列',
  IN: '印度',
  IQ: '伊拉克',
  IR: '伊朗',
  IS: '冰岛',
  IT: '意大利',
  JM: '牙买加',
  JO: '约旦',
  JP: '日本',
  KE: '肯尼亚',
  KG: '吉尔吉斯斯坦',
  KH: '柬埔寨',
  KM: '科摩罗',
  KN: '圣基茨和尼维斯',
  KR: '韩国',
  KW: '科威特',
  KY: '开曼群岛',
  KZ: '哈萨克斯坦',
  LA: '老挝',
  LB: '黎巴嫩',
  LC: '圣卢西亚',
  LK: '斯里兰卡',
  LR: '利比里亚',
  LS: '莱索托',
  LT: '立陶宛',
  LU: '卢森堡',
  LV: '拉脱维亚',
  LY: '利比亚',
  MA: '摩洛哥',
  MC: '摩纳哥',
  MD: '摩尔多瓦',
  ME: '黑山',
  MG: '马达加斯加',
  MK: '北马其顿',
  ML: '马里',
  MM: '缅甸',
  MN: '蒙古',
  MO: '澳门',
  MR: '毛里塔尼亚',
  MS: '蒙特塞拉特',
  MT: '马耳他',
  MU: '毛里求斯',
  MV: '马尔代夫',
  MW: '马拉维',
  MX: '墨西哥',
  MY: '马来西亚',
  MZ: '莫桑比克',
  NA: '纳米比亚',
  NC: '新喀里多尼亚',
  NE: '尼日尔',
  NG: '尼日利亚',
  NI: '尼加拉瓜',
  NL: '荷兰',
  NO: '挪威',
  NP: '尼泊尔',
  NU: '纽埃',
  NZ: '新西兰',
  OM: '阿曼',
  PA: '巴拿马',
  PE: '秘鲁',
  PG: '巴布亚新几内亚',
  PH: '菲律宾',
  PK: '巴基斯坦',
  PL: '波兰',
  PR: '波多黎各',
  PT: '葡萄牙',
  PY: '巴拉圭',
  QA: '卡塔尔',
  RE: '留尼汪',
  RO: '罗马尼亚',
  RS: '塞尔维亚',
  RU: '俄罗斯',
  RW: '卢旺达',
  SA: '沙特阿拉伯',
  SC: '塞舌尔',
  SD: '苏丹',
  SE: '瑞典',
  SG: '新加坡',
  SI: '斯洛文尼亚',
  SK: '斯洛伐克',
  SL: '塞拉利昂',
  SM: '圣马力诺',
  SN: '塞内加尔',
  SO: '索马里',
  SR: '苏里南',
  SS: '南苏丹',
  ST: '圣多美和普林西比',
  SV: '萨尔瓦多',
  SY: '叙利亚',
  SZ: '斯威士兰',
  TD: '乍得',
  TG: '多哥',
  TH: '泰国',
  TJ: '塔吉克斯坦',
  TL: '东帝汶',
  TM: '土库曼斯坦',
  TN: '突尼斯',
  TR: '土耳其',
  TT: '特立尼达和多巴哥',
  TW: '台湾',
  TZ: '坦桑尼亚',
  UA: '乌克兰',
  UG: '乌干达',
  US: '美国',
  UY: '乌拉圭',
  UZ: '乌兹别克斯坦',
  VC: '圣文森特和格林纳丁斯',
  VE: '委内瑞拉',
  VN: '越南',
  VU: '瓦努阿图',
  YE: '也门',
  ZA: '南非',
  ZM: '赞比亚',
  ZW: '津巴布韦',
};

export function countryIdToIso(countryId: string, countryName = '', phoneNumber = ''): string {
  const byId = SMS_ACTIVATE_COUNTRY_ISO[String(countryId || '').trim()];
  if (byId) {
    return byId;
  }
  const byName = countryNameToIso(countryName);
  if (byName) {
    return byName;
  }
  return phoneNumberToCountryIso(phoneNumber, countryName);
}

export function countryIsoToCallingCode(countryIso: string): string {
  return COUNTRY_CALLING_CODES[countryIso.trim().toUpperCase()] || '';
}

export function countryIsoToChineseName(countryIso: string): string {
  return COUNTRY_CHINESE_NAMES[countryIso.trim().toUpperCase()] || '';
}

export function phoneNumberToCountryIso(phoneNumber: string, countryName = ''): string {
  const byName = countryNameToIso(countryName);
  if (byName) {
    return byName;
  }
  const digits = phoneNumber.replace(/[^\d]/g, '');
  if (!digits) {
    return '';
  }
  const matches = Object.entries(COUNTRY_CALLING_CODES)
    .filter(([, code]) => digits.startsWith(code))
    .sort((left, right) => right[1].length - left[1].length);
  if (!matches.length) {
    return '';
  }
  const longestCode = matches[0][1];
  const candidates = matches.filter(([, code]) => code === longestCode).map(([iso]) => iso);
  return candidates.length === 1 ? candidates[0] : '';
}

function countryNameToIso(countryName: string): string {
  const name = countryName.trim().toLowerCase();
  const compactName = name.replace(/[\s_-]+/g, '');
  const direct = COUNTRY_NAME_ISO[name] || COUNTRY_NAME_ISO[compactName] || COUNTRY_NAME_ISO[countryName.trim()];
  if (direct) {
    return direct;
  }
  const normalizedOriginal = countryName.trim();
  if (/^[A-Za-z]{2}$/.test(normalizedOriginal)) {
    return normalizedOriginal.toUpperCase();
  }
  const match = Object.entries(COUNTRY_CHINESE_NAMES).find(([, chineseName]) => chineseName === normalizedOriginal);
  return match?.[0] || '';
}
